config/routes.rb
Rails.application.routes.draw do
  resources :inserts

  root 'inserts#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insert.rb
class Insert < ApplicationRecord
	validates :name, presence: true
	validates :hoa_classification, presence: true
	# validates :hud_id, length: { maximum: 7 }
	#validates :va_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inserts_controller.rb
class InsertsController < ApplicationController
	def new
		@insert = Insert.new
	end

	def create
		@insert = Insert.new(insert_params)

		if @insert.save
			redirect_to @insert
		else
			render 'new'
		end
	end

	def show
		@insert = Insert.find(params[:id])
		respond_to do |format|
			format.html
			format.pdf do
				pdf = InsertPdf.new(@insert)
				send_data pdf.render, filename: '#{@insert.name}_AB_596',
										type: "application/pdf",
										disposition: "inline"
			end
		end
	end

	private
		def insert_params
			params.require(:insert).permit(:name, :hoa_classification, :hud_id, :month_hud_expiration, :day_hud_expiration, :year_hud_expiration, :va_id, :approved)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inserts_helper.rb
module InsertsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inserts/new.html.erb
<div class="container-fluid">
	<div class="jumbotron">
	  <h1 class="display-3 text-center">Create Budget Inserts</h1>
	  <p class="lead text-center">Fill out this form to generate budget inserts that satisfy California Assembly Bill No. 596.</p>
	  <hr class="m-y-2 text-center">
	  <p class="text-center">In order to find out your status for VA and FHA, click on the button below and follow the steps.</p>
	  <p class="lead text-center">
	    <a class="btn btn-primary btn-lg" href="http://www.condoprescreen.com" role="button">Check VA and FHA</a>
	  </p>
	</div>
</div>
<%= bootstrap_form_for :insert, url: inserts_path do |f| %>
	<div class="container bg-info">
			<div class="field">
				<h3>Name of Association</h3>
				<%= f.text_field :name, hide_label: true %>
			</div>
			<div class="field">
				<b>Please Select Condo for a Condominium, Pud for a Planned Unit Development, or Site for a Site Condominium</b>
				<%= f.select :hoa_classification, ["Condo", "Pud", "Site"], :prompt => 'Select One' %>
			</div>
			<div class="field">
				<b>Is Your Association FHA-Approved?</b>
				<%= f.check_box :approved %>
			</div>
			<div class="field">
				<b>What is HUD-assigned id to your association?  It should begin with the letter 'S'.  If you do not have a HUD-assigned id, write None. You do not need to fill this in if you are a Site Condominium or a PUD.</b> <br>
				<%= f.text_field :hud_id, hide_label: true, :placeholder => "Example: S012345" %>
			</div>
			<div class="field">
				<b>What is your date of expiration as assigned by HUD?  You do not need to fill this in if you are a Site Condominium or a PUD.</b> <br>
					<div>
						<%= f.text_field :month_hud_expiration, hide_label: true, :placeholder => "mm" %>
					<div>
					</div>
						<%= f.text_field :day_hud_expiration, hide_label: true, :placeholder => "dd" %>
					</div>
					<div>
					<%= f.text_field :year_hud_expiration, hide_label: true, :placeholder => "yyyy" %>
					</div>
			</div>
			<br>
			<div class="p-x-3"> 
				<b>What is VA-assigned id to your association?  If you do not have a VA number, write None.</b>
				<div class="field">
					<%= f.text_field :va_id, hide_label: true, :placeholder => "Example: 001234" %>
				</div>
			</div>
			<div class="field d-block p-a-3">
				<%= f.submit "Create", class: "btn btn-primary" %>
			</div>
	</div>
	<hr class="m-y-4">
            <div class="col-md-5 text-md-right">
              <small>Condo Approvals, LLC <br> Phone Number: (310) 896-2377</small>
            </div>
          </div>
	
<% end %>

app/views/inserts/show.html.erb
<div class="container-fluid">
	<div class="jumbotron text-center">
		<%= link_to "View Your AB 596", insert_path(@insert, format: "pdf"), class: "btn btn-primary btn-lg" %>
	</div>
	<div class="jumbotron text-center">
		<p class="lead">If You Want To Become Approved For FHA Or VA</p>
	  	<p>Contact Us For A Follow Up To Prescreen Your Community</p>
  		<p class="lead">
    		<a class="btn btn-success btn-lg" href="http://www.condoprescreen.com/form.php" role="button">Click For Prescreen</a>
  		</p>
	</div>
	<hr class="m-y-4">
            <div class="col-md-5 text-md-right">
              <small>Condo Approvals, LLC <br> Phone Number: (310) 896-2377</small>
            </div>
          </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Create Your Budget Insert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>